//
//  This file was auto-generated by Macaw tools 0.10.0-SNAPSHOT version built on Wed, 4 Jul 2018 10:55:39 +0530 
//
package io.zolontech.service.ssa.impl;

import java.lang.Override;

public class HoneybadgerSsaApi implements com.cfx.service.api.Service, io.zolontech.service.ssa.HoneybadgerSsaApi {
  @Override
  public void initialize(com.cfx.service.api.config.Configuration config) throws com.cfx.service.api.ServiceException {
  }

  @Override
  public void start(com.cfx.service.api.StartContext startContext) throws com.cfx.service.api.ServiceException {
  }

  @Override
  public void stop(com.cfx.service.api.StopContext stopContext) throws com.cfx.service.api.ServiceException {
  }

  @Override
  public java.util.List<io.zolontech.service.ssa.Office> getOffices(String officeName) {
    // TODO: Auto-generated code;
    return null;
  }

  @Override
  public io.zolontech.service.ssa.Office getOffice(String officeName) {
    // TODO: Auto-generated code;
    return null;
  }
}
